### PR TITLE
Prod build

### PR DESCRIPTION
**Pull request by kalkins**

### CODE REVIEW

**Comment by kalkins** [comment]
@FredrikAugust @NicolajNiels1 
I've partially fixed the prod build, but there's a problem. When the frontend is trying to query the backend it doesn't use the correct path. It works fine with the dev build.

For example, when logging in it uses `//user/login` instead of `/api/user/login`. There shouldn't be a difference in the docker settings that could cause this. Could it be that the yarn build doesn't respect the `REACT_APP_BASE_URL` environment variable?

**Comment by FredrikAugust** [comment]
@kalkins, no. It is configured to read `REACT_APP_BASE_URL` if it exists, so I don't think that could be the issue. The double-`/` is because the `BASE_URL` is set to `domain.com/`, and it is appended e.g. `/user/login/`, so we get `//`, though this shouldn't affect the application. 

Based on this example

```
$ REACT_APP_SECRET_CODE=prod456 npm build
```

it might seem that the environment variables are _locked_ when building, so they have be set before building.

**Comment by kalkins** [comment]
Okay, the problem was that in docker you have to explicitly set environment variables both during build and runtime, so it wasn't available for `yarn build`. It's fixed now

**Comment by kalkins** [comment]
`yarn build` grinds to a halt on the server...

**Comment by FredrikAugust** [comment]
Any error messages? It should take ~1min, perhaps longer.

**Comment by kalkins** [comment]
It worked after I stopped the old backend docker. The server was probably low on system resources

**Comment by kalkins** [comment]
It's up on `liquidator.kodeworks.nl` now. The backend endpoints and swagger generation seems to work, but when trying to log in the frontend says "NetworkError when attempting to fetch resource.". The nginx log says that it doesn't query the backend at all

**Comment by kalkins** [comment]
It's a CORS error, of course. I tried setting `CORS_ORIGIN_ALLOW_ALL=True` on the server, but it didn't work

**Comment by kalkins** [comment]
Relative REACT_APP_BASE_URL seems to work. I've fixed it on the server, and will be adding the commit after some testing

**Comment by kalkins** [comment]
Should be ready now. It's up on the server, but I haven't been able to set up CD yet

**Pull request merged**
