### PR TITLE
Feature/theme

### LINKED ISSUE #27: Make a draft of the theme object for ThemProvider

### PR DESCRIPTION
**Pull request by NicolajNiels1**
Made new theme object inspired by some of the properties of the Material UI theme object. 

- Closes #27

### CODE REVIEW

**Comment by NicolajNiels1** [comment]
**I'm working on fixing the failed checks.**

**Comment by NicolajNiels1** [comment]
The failed tests have been addressed.
I have also configured storybook with typescript which closes #41

**Comment by NicolajNiels1** [comment]
@FredrikAugust:  A lot of the stories you have written are broken. These are now commented out. They are not complying with the interfaces for the respective components, so TypeScript complains. It is adressed in #50 if you want to fix these yourself

**Comment by FredrikAugust** [comment]
I am aware that this is an issue, and sadly, that's the downside with introducing TypeScript. One of the only good things about JavaScript is that you can simply not give an _otter_ about components not being satisfied with the props they receive. 

I will however address this later this week, but for now I am busy implementing the authentication, which will require quite a bit of work.

Do you think you could resolve the merge conflict locally, and push the changes here? Thanks.

Other than that, looks good! :taco:

**Pull request merged**
